"""Initial MVP schema"""

import sqlalchemy as sa
from alembic import op

revision = "0001_mvp"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "societies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('draft','active','paused')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("oidc_subject", sa.String(length=250), nullable=False),
        sa.Column("oidc_issuer", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oidc_subject"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "devices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_key", sa.String(length=200), nullable=False),
        sa.Column("push_token", sa.String(length=250), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("push_token"),
    )
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "society_invitations",
        sa.Column("society_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["society_id"],
            ["societies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_index(
        op.f("ix_society_invitations_society_id"),
        "society_invitations",
        ["society_id"],
        unique=False,
    )
    op.create_table(
        "towers",
        sa.Column("society_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["society_id"],
            ["societies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("society_id", "name"),
    )
    op.create_index(op.f("ix_towers_society_id"), "towers", ["society_id"], unique=False)
    op.create_table(
        "kitchens",
        sa.Column("society_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tower_id", sa.Uuid(), nullable=False),
        sa.Column("flat", sa.String(length=50), nullable=False),
        sa.Column("pickup_enabled", sa.Boolean(), nullable=False),
        sa.Column("delivery_enabled", sa.Boolean(), nullable=False),
        sa.Column("delivery_fee_paise", sa.Integer(), nullable=False),
        sa.Column("upi_id", sa.String(length=150), nullable=True),
        sa.Column("fssai_number", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('pending','approved','suspended')"),
        sa.CheckConstraint("delivery_fee_paise >= 0"),
        sa.CheckConstraint("pickup_enabled OR delivery_enabled"),
        sa.ForeignKeyConstraint(
            ["society_id"],
            ["societies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tower_id"],
            ["towers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kitchens_society_id"), "kitchens", ["society_id"], unique=False)
    op.create_table(
        "society_memberships",
        sa.Column("society_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tower_id", sa.Uuid(), nullable=False),
        sa.Column("flat", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('pending','active','suspended')"),
        sa.ForeignKeyConstraint(
            ["society_id"],
            ["societies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tower_id"],
            ["towers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("society_id", "user_id"),
    )
    op.create_index(
        op.f("ix_society_memberships_society_id"),
        "society_memberships",
        ["society_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_society_memberships_user_id"), "society_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "dishes",
        sa.Column("kitchen_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kitchen_id"],
            ["kitchens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dishes_kitchen_id"), "dishes", ["kitchen_id"], unique=False)
    op.create_table(
        "kitchen_members",
        sa.Column("kitchen_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.CheckConstraint("role IN ('owner','manager')"),
        sa.ForeignKeyConstraint(
            ["kitchen_id"],
            ["kitchens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("kitchen_id", "user_id"),
    )
    op.create_table(
        "orders",
        sa.Column(
            "order_number", sa.BigInteger(), sa.Identity(always=False, start=1001), nullable=False
        ),
        sa.Column("society_id", sa.Uuid(), nullable=False),
        sa.Column("kitchen_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("fulfillment_type", sa.String(length=20), nullable=False),
        sa.Column("customer_note", sa.String(length=1000), nullable=True),
        sa.Column("kitchen_name", sa.String(length=150), nullable=False),
        sa.Column("pickup_address", sa.JSON(), nullable=False),
        sa.Column("delivery_address", sa.JSON(), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subtotal_paise", sa.Integer(), nullable=False),
        sa.Column("delivery_fee_paise", sa.Integer(), nullable=False),
        sa.Column("total_paise", sa.Integer(), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("upi_id", sa.String(length=150), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preparing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fulfillment_type IN ('pickup','delivery')"),
        sa.CheckConstraint("payment_status IN ('unpaid','customer_reported','kitchen_confirmed')"),
        sa.CheckConstraint(
            "status IN ('pending','accepted','preparing','ready','completed',"
            "'rejected','cancelled','expired')"
        ),
        sa.CheckConstraint("subtotal_paise >= 0 AND delivery_fee_paise >= 0"),
        sa.CheckConstraint("total_paise = subtotal_paise + delivery_fee_paise"),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kitchen_id"],
            ["kitchens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["society_id"],
            ["societies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number"),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_kitchen_id"), "orders", ["kitchen_id"], unique=False)
    op.create_index(
        "ix_orders_kitchen_status", "orders", ["kitchen_id", "status", "created_at"], unique=False
    )
    op.create_table(
        "menu_listings",
        sa.Column("kitchen_id", sa.Uuid(), nullable=False),
        sa.Column("dish_id", sa.Uuid(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_paise", sa.Integer(), nullable=False),
        sa.Column("quantity_total", sa.Integer(), nullable=False),
        sa.Column("quantity_reserved", sa.Integer(), nullable=False),
        sa.Column("pickup_enabled", sa.Boolean(), nullable=False),
        sa.Column("delivery_enabled", sa.Boolean(), nullable=False),
        sa.Column("delivery_fee_paise", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('draft','published','cancelled')"),
        sa.CheckConstraint("available_from < available_until"),
        sa.CheckConstraint("delivery_fee_paise >= 0"),
        sa.CheckConstraint("order_cutoff <= available_until"),
        sa.CheckConstraint("pickup_enabled OR delivery_enabled"),
        sa.CheckConstraint("price_paise >= 0"),
        sa.CheckConstraint("quantity_reserved >= 0 AND quantity_reserved <= quantity_total"),
        sa.CheckConstraint("quantity_total > 0"),
        sa.ForeignKeyConstraint(
            ["dish_id"],
            ["dishes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kitchen_id"],
            ["kitchens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_listings_feed", "menu_listings", ["service_date", "status", "kitchen_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_listings_kitchen_id"), "menu_listings", ["kitchen_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "order_events",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.create_table(
        "order_idempotency",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("customer_id", "key"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("menu_listing_id", sa.Uuid(), nullable=False),
        sa.Column("dish_name", sa.String(length=150), nullable=False),
        sa.Column("unit_price_paise", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_paise", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity > 0 AND unit_price_paise >= 0"),
        sa.CheckConstraint("total_paise = quantity * unit_price_paise"),
        sa.ForeignKeyConstraint(
            ["menu_listing_id"],
            ["menu_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "menu_listing_id"),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_table("order_idempotency")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_menu_listings_kitchen_id"), table_name="menu_listings")
    op.drop_index("ix_listings_feed", table_name="menu_listings")
    op.drop_table("menu_listings")
    op.drop_index("ix_orders_kitchen_status", table_name="orders")
    op.drop_index(op.f("ix_orders_kitchen_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("kitchen_members")
    op.drop_index(op.f("ix_dishes_kitchen_id"), table_name="dishes")
    op.drop_table("dishes")
    op.drop_index(op.f("ix_society_memberships_user_id"), table_name="society_memberships")
    op.drop_index(op.f("ix_society_memberships_society_id"), table_name="society_memberships")
    op.drop_table("society_memberships")
    op.drop_index(op.f("ix_kitchens_society_id"), table_name="kitchens")
    op.drop_table("kitchens")
    op.drop_index(op.f("ix_towers_society_id"), table_name="towers")
    op.drop_table("towers")
    op.drop_index(op.f("ix_society_invitations_society_id"), table_name="society_invitations")
    op.drop_table("society_invitations")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("users")
    op.drop_table("societies")
    # ### end Alembic commands ###
