"""Export both contracts without connecting to the database."""

import json
import os
from pathlib import Path

# Contract generation uses explicit nonproduction settings, never deployment credentials.
os.environ["KITCHEN_ENVIRONMENT"] = "test"

from kitchen_admin_api.main import create_app as create_admin_app
from kitchen_api.main import create_app
from kitchen_core.community_types import CommunityType

directory = Path("docs/openapi")
directory.mkdir(parents=True, exist_ok=True)
for name, app in (("api", create_app()), ("admin", create_admin_app())):
    (directory / f"{name}.json").write_text(json.dumps(app.openapi(), indent=2) + "\n")

# Generate label/slug choices alongside contracts from the same backend enum.

choices_path = Path("apps/admin/src/lib/api/community-type-choices.ts")
choices_path.write_text(
    "// Generated by scripts/export_openapi.py. Do not edit.\n"
    'import type { CommunityType } from "./generated/models";\n\n'
    "export const communityTypeChoices = "
    + json.dumps(CommunityType.choices(), indent=2)
    + " as const satisfies readonly { slug: CommunityType; label: string }[];\n\n"
    + "export const communityTypeLabels = Object.fromEntries(\n"
    + "  communityTypeChoices.map(({ slug, label }) => [slug, label]),\n"
    + ") as Record<CommunityType, string>;\n"
)
