// Generated by scripts/export_openapi.py. Do not edit.
import type { CommunityType } from "./generated/models";

export const communityTypeChoices = [
  {
    "slug": "residential_society",
    "label": "Residential society"
  },
  {
    "slug": "cantonment",
    "label": "Cantonment"
  },
  {
    "slug": "housing_colony",
    "label": "Housing colony"
  },
  {
    "slug": "university",
    "label": "University"
  },
  {
    "slug": "corporate_campus",
    "label": "Corporate campus"
  },
  {
    "slug": "gated_community",
    "label": "Gated community"
  },
  {
    "slug": "other",
    "label": "Other"
  }
] as const satisfies readonly { slug: CommunityType; label: string }[];

export const communityTypeLabels = Object.fromEntries(
  communityTypeChoices.map(({ slug, label }) => [slug, label]),
) as Record<CommunityType, string>;
